site_name: Awesome Python
site_url: https://awesome-python.com
site_description: A curated list of awesome Python frameworks, libraries and software
site_author: Prakash
repo_name: PrakasRavichandran/Introduction-to-Python
repo_url: https://github.com/PrakasRavichandran/Introduction-to-Python
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/PrakasRavichandran
    - type: twitter
      link: https://twitter.com/ 
    - type: linkedin
      link: https://www.linkedin.com
google_analytics:
  - UA-510626-7
  - auto
extra_css:
    - css/extra.css
nav:
  - "Life is short, you need Python.": "index.md"
